export const currencyList = [
  { value: "INR", label: "Indian Rupee - INR" },
  { value: "USD", label: "United States Dollar - USD" },
  { value: "EUR", label: "Euro - EUR" },
  { value: "GBP", label: "British Pound - GBP" },
  { value: "AUD", label: "Australian Dollar - AUD" },
  { value: "CAD", label: "Canadian Dollar - CAD" },
  { value: "JPY", label: "Japanese Yen - JPY" },
  { value: "BYR", label: "Belarusian Ruble - BYR" },
  { value: "AED", label: "United Arab Emirates Dirham - AED" },
  { value: "AFN", label: "Afghan Afghani - AFN" },
  { value: "ALL", label: "Albanian Lek - ALL" },
  { value: "AMD", label: "Armenian Dram - AMD" },
  { value: "ANG", label: "Netherlands Antillean Gulden - ANG" },
  { value: "AOA", label: "Angolan Kwanza - AOA" },
  { value: "ARS", label: "Argentine Peso - ARS" },
  { value: "AWG", label: "Aruban Florin - AWG" },
  { value: "AZN", label: "Azerbaijani Manat - AZN" },
  { value: "BAM", label: "Bosnia and Herzegovina Convertible Mark - BAM" },
  { value: "BBD", label: "Barbadian Dollar - BBD" },
  { value: "BDT", label: "Bangladeshi Taka - BDT" },
  { value: "BGN", label: "Bulgarian Lev - BGN" },
  { value: "BHD", label: "Bahraini Dinar - BHD" },
  { value: "BIF", label: "Burundian Franc - BIF" },
  { value: "BMD", label: "Bermudian Dollar - BMD" },
  { value: "BND", label: "Brunei Dollar - BND" },
  { value: "BOB", label: "Bolivian Boliviano - BOB" },
  { value: "BRL", label: "Brazilian Real - BRL" },
  { value: "BSD", label: "Bahamian Dollar - BSD" },
  { value: "BTC", label: "Bitcoin - BTC" },
  { value: "BTN", label: "Bhutanese Ngultrum - BTN" },
  { value: "BWP", label: "Botswana Pula - BWP" },
  { value: "BYN", label: "Belarusian Ruble - BYN" },
  { value: "BZD", label: "Belize Dollar - BZD" },
  { value: "CDF", label: "Congolese Franc - CDF" },
  { value: "CHF", label: "Swiss Franc - CHF" },
  { value: "CLF", label: "Unidad de Fomento - CLF" },
  { value: "CLP", label: "Chilean Peso - CLP" },
  { value: "CNY", label: "Chinese Renminbi Yuan - CNY" },
  { value: "COP", label: "Colombian Peso - COP" },
  { value: "CRC", label: "Costa Rican Colón - CRC" },
  { value: "CUC", label: "Cuban Convertible Peso - CUC" },
  { value: "CUP", label: "Cuban Peso - CUP" },
  { value: "CVE", label: "Cape Verdean Escudo - CVE" },
  { value: "CZK", label: "Czech Koruna - CZK" },
  { value: "DJF", label: "Djiboutian Franc - DJF" },
  { value: "DKK", label: "Danish Krone - DKK" },
  { value: "DOP", label: "Dominican Peso - DOP" },
  { value: "DZD", label: "Algerian Dinar - DZD" },
  { value: "EEK", label: "Estonian Kroon - EEK" },
  { value: "EGP", label: "Egyptian Pound - EGP" },
  { value: "ERN", label: "Eritrean Nakfa - ERN" },
  { value: "ETB", label: "Ethiopian Birr - ETB" },
  { value: "FJD", label: "Fijian Dollar - FJD" },
  { value: "FKP", label: "Falkland Pound - FKP" },
  { value: "GBX", label: "British Penny - GBX" },
  { value: "GEL", label: "Georgian Lari - GEL" },
  { value: "GGP", label: "Guernsey Pound - GGP" },
  { value: "GHS", label: "Ghanaian Cedi - GHS" },
  { value: "GIP", label: "Gibraltar Pound - GIP" },
  { value: "GMD", label: "Gambian Dalasi - GMD" },
  { value: "GNF", label: "Guinean Franc - GNF" },
  { value: "GTQ", label: "Guatemalan Quetzal - GTQ" },
  { value: "GYD", label: "Guyanese Dollar - GYD" },
  { value: "HKD", label: "Hong Kong Dollar - HKD" },
  { value: "HNL", label: "Honduran Lempira - HNL" },
  { value: "HRK", label: "Croatian Kuna - HRK" },
  { value: "HTG", label: "Haitian Gourde - HTG" },
  { value: "HUF", label: "Hungarian Forint - HUF" },
  { value: "IDR", label: "Indonesian Rupiah - IDR" },
  { value: "ILS", label: "Israeli New Sheqel - ILS" },
  { value: "IMP", label: "Isle of Man Pound - IMP" },
  { value: "IQD", label: "Iraqi Dinar - IQD" },
  { value: "IRR", label: "Iranian Rial - IRR" },
  { value: "ISK", label: "Icelandic Króna - ISK" },
  { value: "JEP", label: "Jersey Pound - JEP" },
  { value: "JMD", label: "Jamaican Dollar - JMD" },
  { value: "JOD", label: "Jordanian Dinar - JOD" },
  { value: "KES", label: "Kenyan Shilling - KES" },
  { value: "KGS", label: "Kyrgyzstani Som - KGS" },
  { value: "KHR", label: "Cambodian Riel - KHR" },
  { value: "KMF", label: "Comorian Franc - KMF" },
  { value: "KPW", label: "North Korean Won - KPW" },
  { value: "KRW", label: "South Korean Won - KRW" },
  { value: "KWD", label: "Kuwaiti Dinar - KWD" },
  { value: "KYD", label: "Cayman Islands Dollar - KYD" },
  { value: "KZT", label: "Kazakhstani Tenge - KZT" },
  { value: "LAK", label: "Lao Kip - LAK" },
  { value: "LBP", label: "Lebanese Pound - LBP" },
  { value: "LKR", label: "Sri Lankan Rupee - LKR" },
  { value: "LRD", label: "Liberian Dollar - LRD" },
  { value: "LSL", label: "Lesotho Loti - LSL" },
  { value: "LTL", label: "Lithuanian Litas - LTL" },
  { value: "LVL", label: "Latvian Lats - LVL" },
  { value: "LYD", label: "Libyan Dinar - LYD" },
  { value: "MAD", label: "Moroccan Dirham - MAD" },
  { value: "MDL", label: "Moldovan Leu - MDL" },
  { value: "MGA", label: "Malagasy Ariary - MGA" },
  { value: "MKD", label: "Macedonian Denar - MKD" },
  { value: "MMK", label: "Myanmar Kyat - MMK" },
  { value: "MNT", label: "Mongolian Tögrög - MNT" },
  { value: "MOP", label: "Macanese Pataca - MOP" },
  { value: "MRO", label: "Mauritanian Ouguiya - MRO" },
  { value: "MTL", label: "Maltese Lira - MTL" },
  { value: "MUR", label: "Mauritian Rupee - MUR" },
  { value: "MVR", label: "Maldivian Rufiyaa - MVR" },
  { value: "MWK", label: "Malawian Kwacha - MWK" },
  { value: "MXN", label: "Mexican Peso - MXN" },
  { value: "MYR", label: "Malaysian Ringgit - MYR" },
  { value: "MZN", label: "Mozambican Metical - MZN" },
  { value: "NAD", label: "Namibian Dollar - NAD" },
  { value: "NGN", label: "Nigerian Naira - NGN" },
  { value: "NIO", label: "Nicaraguan Córdoba - NIO" },
  { value: "NOK", label: "Norwegian Krone - NOK" },
  { value: "NPR", label: "Nepalese Rupee - NPR" },
  { value: "NZD", label: "New Zealand Dollar - NZD" },
  { value: "OMR", label: "Omani Rial - OMR" },
  { value: "PAB", label: "Panamanian Balboa - PAB" },
  { value: "PEN", label: "Peruvian Sol - PEN" },
  { value: "PGK", label: "Papua New Guinean Kina - PGK" },
  { value: "PHP", label: "Philippine Peso - PHP" },
  { value: "PKR", label: "Pakistani Rupee - PKR" },
  { value: "PLN", label: "Polish Złoty - PLN" },
  { value: "PYG", label: "Paraguayan Guaraní - PYG" },
  { value: "QAR", label: "Qatari Riyal - QAR" },
  { value: "RON", label: "Romanian Leu - RON" },
  { value: "RSD", label: "Serbian Dinar - RSD" },
  { value: "RUB", label: "Russian Ruble - RUB" },
  { value: "RWF", label: "Rwandan Franc - RWF" },
  { value: "SAR", label: "Saudi Riyal - SAR" },
  { value: "SBD", label: "Solomon Islands Dollar - SBD" },
  { value: "SCR", label: "Seychellois Rupee - SCR" },
  { value: "SDG", label: "Sudanese Pound - SDG" },
  { value: "SEK", label: "Swedish Krona - SEK" },
  { value: "SGD", label: "Singapore Dollar - SGD" },
  { value: "SHP", label: "Saint Helenian Pound - SHP" },
  { value: "SKK", label: "Slovak Koruna - SKK" },
  { value: "SLL", label: "Sierra Leonean Leone - SLL" },
  { value: "SOS", label: "Somali Shilling - SOS" },
  { value: "SRD", label: "Surinamese Dollar - SRD" },
  { value: "SSP", label: "South Sudanese Pound - SSP" },
  { value: "STD", label: "São Tomé and Príncipe Dobra - STD" },
  { value: "SVC", label: "Salvadoran Colón - SVC" },
  { value: "SYP", label: "Syrian Pound - SYP" },
  { value: "SZL", label: "Swazi Lilangeni - SZL" },
  { value: "THB", label: "Thai Baht - THB" },
  { value: "TJS", label: "Tajikistani Somoni - TJS" },
  { value: "TMM", label: "Turkmenistani Manat - TMM" },
  { value: "TMT", label: "Turkmenistani Manat - TMT" },
  { value: "TND", label: "Tunisian Dinar - TND" },
  { value: "TOP", label: "Tongan Paʻanga - TOP" },
  { value: "TRY", label: "Turkish Lira - TRY" },
  { value: "TTD", label: "Trinidad and Tobago Dollar - TTD" },
  { value: "TWD", label: "New Taiwan Dollar - TWD" },
  { value: "TZS", label: "Tanzanian Shilling - TZS" },
  { value: "UAH", label: "Ukrainian Hryvnia - UAH" },
  { value: "UGX", label: "Ugandan Shilling - UGX" },
  { value: "UYU", label: "Uruguayan Peso - UYU" },
  { value: "UZS", label: "Uzbekistan Som - UZS" },
  { value: "VEF", label: "Venezuelan Bolívar - VEF" },
  { value: "VND", label: "Vietnamese Đồng - VND" },
  { value: "VUV", label: "Vanuatu Vatu - VUV" },
  { value: "WST", label: "Samoan Tala - WST" },
  { value: "XAF", label: "Central African Cfa Franc - XAF" },
  { value: "XAG", label: "Silver (Troy Ounce) - XAG" },
  { value: "XAU", label: "Gold (Troy Ounce) - XAU" },
  { value: "XBA", label: "European Composite Unit - XBA" },
  { value: "XBB", label: "European Monetary Unit - XBB" },
  { value: "XBC", label: "European Unit of Account 9 - XBC" },
  { value: "XBD", label: "European Unit of Account 17 - XBD" },
  { value: "XCD", label: "East Caribbean Dollar - XCD" },
  { value: "XDR", label: "Special Drawing Rights - XDR" },
  { value: "XFU", label: "UIC Franc - XFU" },
  { value: "XOF", label: "West African Cfa Franc - XOF" },
  { value: "XPD", label: "Palladium - XPD" },
  { value: "XPF", label: "Cfp Franc - XPF" },
  { value: "XPT", label: "Platinum - XPT" },
  { value: "YER", label: "Yemeni Rial - YER" },
  { value: "ZAR", label: "South African Rand - ZAR" },
  { value: "ZMK", label: "Zambian Kwacha - ZMK" },
  { value: "ZMW", label: "Zambian Kwacha - ZMW" },
  { value: "ZWD", label: "Zimbabwean Dollar - ZWD" },
  { value: "ZWL", label: "Zimbabwean Dollar - ZWL" },
  { value: "ZWN", label: "Zimbabwean Dollar - ZWN" },
  { value: "ZWR", label: "Zimbabwean Dollar - ZWR" },
];
